export const VEHICLE_REQUESTED = 'VEHICLE_REQUESTED';
export const VEHICLE_REQUEST_SUCCESS = 'VEHICLE_REQUEST_SUCCESS';
export const VEHICLE_REQUEST_ERROR = 'VEHICLE_REQUEST_ERROR';
export const VEHICLE_RESERVING = 'VEHICLE_RESERVING';
export const VEHICLE_RESERVE_SUCCESS = 'VEHICLE_RESERVE_SUCCESS';
export const VEHICLE_RESERVE_ERROR = 'VEHICLE_RESERVE_ERROR';
